gamestate
    main_menu --> shopping
    main_menu --> settings
    settings --> main_menu
    flying --> win
    flying --> lose
    flying --> paused
    paused --> flying
    paused --> main_menu
    win --> shopping
    lose --> shopping
    shopping --> flying
    shopping --> main_menu
